# Generated by Django 4.2.30 on 2026-04-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('dia_inteiro', models.BooleanField(default=False, verbose_name='Dia inteiro?')),
                ('data_hora', models.DateTimeField(verbose_name='Data/Horário')),
                ('ciclo', models.CharField(choices=[('unico', 'Único'), ('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='unico', max_length=20, verbose_name='Ciclo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_hora', '-criado_em'],
            },
        ),
    ]