# Generated by Django 4.2.30 on 2026-04-11 17:43

from django.db import migrations, models
import eventos.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data_hora',
            field=models.DateTimeField(blank=True, null=True, validators=[eventos.models.validar_data], verbose_name='Data/Horário'),
        ),
    ]
